dnd-side-project/dnd-10th-3-frontend

src/components/common/divider/Divider.stories.tsx
src/components/common/divider/Divider.tsx
src/components/common/divider/index.ts
src/components/common/divider/variant.tsx

Divider 컴포넌트와 DIvider 스토리북을 작성했습니다.
close #37 
추후 디자인 수정 필요합니다.

[FEAT] Divider 컴포넌트, 스토리북

---

package.json
src/components/common/bottomSheet/BottomSheet.stories.tsx
src/components/common/bottomSheet/BottomSheet.tsx
src/components/common/bottomSheet/index.ts
src/components/common/bottomSheet/style.css
src/components/common/button/Button.tsx
yarn.lock

react-spring-bottom-sheet 의존성을 설치하고 기본적인 스토리 구현하였습니다.
추후 완료하여 사진 추가할게요!! 아직 수정할 사항들이 있어서요! 
상대 경로 지정하려고 해요!!

[FEAT] BottomSheet 스토리 작성 

---

src/components/common/button/Button.stories.tsx
src/components/common/button/Button.tsx
src/components/common/button/index.ts
src/components/common/button/types.ts
src/components/common/button/variant.tsx

버튼 컴포넌트, 스토리북 작성
`iconOnly` 또는 `children` 둘 중 하나만 채우게끔 제한해 두었어요.
1. 아이콘만 있는 버튼 사용법
`iconOnly` props 추가 필수, `children` props 채울 수 없음
```tsx
<button icon='아이콘이름' iconOnly></button>
<button icon='아이콘이름' iconOnly />
```
2. 아이콘+텍스트 있는 버튼 사용법
`children` props 채워야 함, iconOnly 추가할 필요 없음 (false로 처리됨)
```tsx
<button icon='🥹'>텍스트</button> // 🥹 텍스트
<button icon='🥹' iconSide='right'>텍스트</button> // 텍스트 🥹
```
+스토리북 보시면 이해가 더 잘 되실 것 같아요.
close #36
라우팅에 사용되는 Link는 버튼 범주에 포함시켜야할까요 아니면 따로 Link 컴포넌트를 둘까요?
버튼 컴포넌트를 Link로 래핑해 사용할지, 단독 Link 할지 정하면 좋을 것 같아요~

[FEAT] button 컴포넌트, 스토리북

---

.eslintrc.json
.prettierrc

Eslint만 순서 수정을 담당하도록 prettier의 순서 수정을 막았습니다.
eslint 룰에 맞춥니다.
close #49 
- [prettier와 eslint-plugin-tailwindcss의 클래스 순서 충돌 이슈](https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/231)
- [해결에 참고한 이슈](https://github.com/prettier/eslint-plugin-prettier/issues/610)

[BUGFIX] eslint가 tailwind classname 순서 변경을 담당하도록 제한

---

src/components/common/progressBar/ProgressBar.stories.tsx
src/components/common/progressBar/ProgressBar.tsx
src/components/common/progressBar/index.ts
src/components/common/progressBar/variant.tsx

1. 프로그래스바 컴포넌트와 스터리 구현하려고 합니다.

[FEAT] ProgressBar 컴포넌트 및 스토리 작성 

---

next.config.mjs

next.config에 svgr 설정 추가했습니다.
close #54  
[참고한 자료](https://velog.io/@leejaehyuck9/TSNext.js에서-SVG-컴포넌트로-사용하기)

[BUGFIX] next 환경에서 SVG 컴포넌트 에러

---

src/components/common/input/Input.tsx
src/components/common/tag/Tag.stories.tsx
src/components/common/tag/Tag.tsx
src/components/common/tag/index.ts
src/components/common/tag/variant.tsx

[FEAT] Tag 공통 컴포넌트 작성 

---

src/components/common/button/Button.stories.tsx
src/components/common/button/Button.tsx
src/components/common/button/variant.tsx

- iconOnly Button 컴포넌트에 사용하기 적합한 `empty` variant를 추가했습니다.
`empty`는 세 번째 라인과 같이 배경 색이 없는 variant입니다.
다음 형태로 아이콘 버튼을 표현할 수 있습니다.
```tsx
<icon variant='empty' icon='filledHeart' iconOnly />
```
close #64 
- Header에 요 empty iconOnly 버튼 children으로 넣어 사용하면 좋을 것 같아요.

[FEAT] Button 컴포넌트에 `empty` variant 추가 

---

src/app/layout.tsx
src/app/login/page.tsx
src/components/AuthButton/KakaoLoginButton.tsx
src/components/AuthButton/index.ts
src/components/layout/header/Header.tsx
styles/theme/colors.ts

로그인 페이지 UI 작업 했습니다.
*아이폰 SE 기준입니다.
close #26 
- **혹시 글자가 작아보이진 않나요? 피그마와 똑같게 하긴 했는데 폰으로 확인해 보니 조금 더 커도 괜찮겠다는 생각이 듭니다.**
- 디자인 수정된 카카오 로그인 버튼이 적용된 UI 입니다. (2/5 기준)

[FEAT] 로그인 페이지 UI

---

src/app/vote/_component/VoteHeader.tsx
src/components/layout/header/Header.tsx

- Test 페이지와 Vote 페이지 헤더 패딩 및 마진 변경으로 인한 UI 수정하였습니다. 
- test Page 이전
- 이후 
- vote page 이전
- 이후

[BUGFIX] header 수정 후 사이드 이팩트 해결

---

src/app/test/page.tsx
src/app/testing/page.tsx
src/app/vote/page.tsx
src/components/common/button/variant.tsx
src/components/common/input/variant.tsx

- 모든 버튼 radius 12px로 통일하였습니다. 
- 스크롤이 없는 단일 페이지에서 하단 여백은 20px로 통일하였습니다. (test 페이지) 
- Input 입력 전/후 및 Focus시 디자인 반영하였습니다. 하지만 검색 Focus시 디자인은 반영하지 않고 넘어갔습니다.

[DESIGN] 디자인 피드백 반영하여 변경된 디자인 작업 

---

src/components/common/button/Button.tsx
src/components/common/button/Button.variant.tsx
src/components/common/radio/Radio.variant.tsx
styles/theme/boxShadow.ts

- 버튼 색깔 변경(기본 버튼, 서브 버튼, 비활성화 버튼)
- 버튼 border radius 16px로 변경 (rounded-lg)
- 라디오 버튼 색깔 변경
close #81

[DESIGN] 버튼, 라디오 버튼 색깔 변경

---

tailwind.config.ts

tailwind.config.ts 하위 내용을 수정하였습니다. 
```ts
mainGradient: 'linear-gradient(0deg, rgb(255,255,255,1) 0%, rgb(251,241,248,1) 100%)',
```

[DESIGN] 디자인 변경 사항에 따른 Gradient 배경 수정

---

src/components/common/input/Input.stories.tsx

[HOTFIX] vercel 배포시 에러 해결 

---

src/app/vote/create/_components/CategorySelector.tsx
src/app/vote/create/_components/CreateVoteForm.tsx
src/app/vote/create/_components/VoteDateForm.tsx
src/app/vote/create/_components/VoteForm.tsx
src/app/vote/create/_components/index.ts
src/app/vote/create/page.tsx
src/components/common/bottomSheet/BottomSheet.tsx
src/components/features/vote/voteItem/components/Input.tsx
src/components/layout/header/Header.tsx
src/components/shared/index.ts
src/components/shared/letterCounter/LetterCounter.tsx
src/components/shared/optionButton/OptionButton.tsx
src/constants/category.ts

- 투표 작성하기 UI 작업
https://github.com/dnd-side-project/dnd-10th-3-frontend/assets/69228045/a5505561-4195-4047-bbbd-22f54f10cacd
close #39 
- 버튼이나 글자수 세기 등의 기능은 동작하지 않습니다.
- 날짜 선택 모달은 디자인이 나오지 않아서 구현하지 않았습니다.

[FEAT] 투표 작성하기 페이지 UI 작업

---

src/app/test/_components/TestForm.tsx

- /test 페이지 레이아웃 수정 (버튼 이슈, 중복 적용된 좌우 패딩 제거)
- 변경된 디자인(버튼, 문구 컬러) 적용
*아이폰 13 mini 기준
*gif 화질이 낮아 그라데이션 이상해보이지만 실제론 문제없습니다.

[DESIGN] test 시작 페이지 레이아웃, 디자인 수정

---

src/app/test/result/_components/ResultContents.tsx

머지한 후, VoteITem.Span을 변경하지 않은 부분이 있어 빠르게 변경하였습니다.

[FIX] 테스트 결과 페이지 VoteItem.Text으로 변경 

---

src/app/mypage/page.tsx
src/app/test/_components/TestForm.tsx
src/app/vote/_component/VoteHeader.tsx
src/components/common/tabs/Tabs.stories.tsx
src/components/layout/header/Header.stories.tsx
src/components/layout/header/Header.tsx
src/components/layout/header/components/Previous.tsx
src/components/layout/header/components/ToggleNav.tsx
src/components/layout/header/components/index.ts
src/constants/category.ts
src/constants/mypage.ts
src/constants/tab.ts
src/constants/toggleNav.ts

- 기존 Header.Tab을 Header.ToggleNav로 변경했습니다. (카테고리 선택하는 Tabs와 헷갈릴 수 있기에)
- ToggleNav에서 상태를 제거하고 pathname에 따라 토글이 변경되도록 변경했습니다.
close #119

[BUGFIX] 토글 동작 이상 해결 (pathname과 토글 연결)

---

src/app/vote/create/_components/CreateVoteForm.tsx
src/app/vote/create/_components/VoteForm.tsx
src/app/vote/create/_components/VoteItemImgForm.tsx
src/app/vote/create/_components/index.ts
src/components/shared/imgUploadButton/ImageUploadButton.tsx
src/components/shared/index.ts
src/constants/toast.ts
src/hooks/index.ts
src/hooks/useImageUpload.ts
src/schema/CreateVoteSchema.ts

- 투표 만들기 폼의 투표 항목에 이미지 첨부를 할 수 있고, 첨부한 이미지를 보여주는(preview) 기능
close #107

[FEAT] 투표 만들기 폼에 이미지 첨부 기능

---

src/app/test/_components/TestQuestionTemplate.tsx
src/app/vote/_component/VoteLayout.tsx
src/app/vote/page.tsx
src/components/common/input/variant.tsx
src/constants/test/step.tsx

- 테스트 진행 페이지 버튼 색과 Tag 반영하였습니다.
- 투표 페이지 하단 플로팅 버튼과 검색 인풋 색상을 변경하였습니다.

[DESIGN] 테스트 및 커뮤니티 변경된 디자인 반영 

---

src/app/test/_components/TestQuestionTemplate.tsx
src/app/vote/page.tsx
src/components/common/button/Button.stories.tsx
src/components/common/button/Button.tsx
src/components/common/button/Button.variant.tsx
src/components/common/button/types.ts
tailwind.config.ts

- accent 버튼을 추가했어요. (스토리북 참고)
- 이 버라이언트에는 hover, focus 효과가 적용되어 있습니다.
- iconSide가 left, right일때 아이콘이 렌더링 되지 않는 이슈가 있어서(조건문 오류) both 삭제했습니다.
close #135

[DESIGN] 버튼 accent 버라이언트 추가

---

README.md

[FIX] READMD.md 배포 url 변경

---

src/app/vote/[slug]/_component/Replies.tsx
src/app/vote/[slug]/_component/VoteExtraDetail.tsx
src/app/vote/[slug]/_component/index.ts
src/app/vote/[slug]/layout.tsx
src/app/vote/[slug]/page.tsx
src/components/common/divider/Divider.variant.ts
src/components/features/vote/index.ts
src/components/features/vote/reply/Reply.stories.tsx
src/components/features/vote/reply/Reply.tsx
src/components/features/vote/reply/index.ts
src/components/features/vote/voteCard/components/Header.tsx
src/components/features/vote/voteCard/variants.ts
src/components/shared/index.ts
src/components/shared/notice/Notice.tsx
src/components/shared/profile/Profile.tsx
src/components/shared/replyInput/ReplyInput.tsx
styles/theme/boxShadow.ts

- 투표 상세 페이지 UI 작업 (단순 UI 그리기이고 로직은 없습니다)
close #130

[DESIGN] 투표 상세 페이지 UI

---

next.config.mjs
src/app/test/result/[id]/_components/ResultContents.tsx
src/app/vote/[slug]/_component/VoteDetail.tsx
src/app/vote/[slug]/_component/Voting.tsx
src/app/vote/[slug]/_component/index.ts
src/app/vote/[slug]/page.tsx
src/app/vote/_component/VoteContents.tsx
src/components/common/tag/Tag.tsx
src/components/features/vote/voteCard/VoteCard.stories.tsx
src/components/features/vote/voteCard/components/Header.tsx
src/components/features/vote/voteItem/components/Progress.tsx
src/hooks/vote/useGetVoteById.ts
src/hooks/vote/useVotingMutation.ts
src/types/vote/vote.ts
src/utils/dates/fromNowOf.ts
src/utils/dates/index.ts
src/utils/dates/isPast.ts

[FEAT] 투표 상세 페이지, 투표 참여하기 기능

---

next.config.mjs

[BUGFIX] 임시로 StrictMode False로 변경 

---

package.json
src/constants/test/step.tsx
yarn.lock

close #165
- @toss/hangul 라이브러리 내부에 있는 josa 라이브러리를 활용하였습니다. index.d.ts도 지원하여 타입을 지원해주는 라이브러리이며 최신에 업데이트되고 있어 선정하게 됐습니다. 
- 받침이 있는 이름과 없는 이름을 분별하여 조사를 다르게 제공해줍니다.

[FEAT] 라이브러리 활용하여 테스트 진행시 조사 값에 따라 적용하도록 구현 

---

src/app/vote/_component/VoteContents.tsx
src/components/features/vote/voteItem/VoteItem.variant.ts
src/components/features/vote/voteItem/components/Progress.tsx
styles/theme/boxShadow.ts

- VoteItem 배경 색깔 gray-100 -> gray-50 수정
- VoteContent 배경 그림자 shadow-thumb -> shadow-vote-card 수정(그림자 추가됨)
왼쪽이 After / 오른쪽이 Before 입니다.
- 디자인 시안과 묘하게 다른 것 같아서 확인했더니 색깔이 달라졌더라구요, VoteContent 그림자도 디자인상 하단에만 있어서 함께 수정했습니다.
- 참고로 디자인에 검색창 보더도 없더라구요..!! 인풋은 제가 잘 몰라서 수정하지 않았습니다. 주영님이 추후 확인 부탁드립니다~

[DESIGN] VoteItem 배경 색깔, VoteContent 배경 그림자 수정

---

package.json
src/app/vote/[slug]/_component/Replies.tsx
src/components/common/controlTab/ControlTab.stories.tsx
src/components/common/controlTab/ControlTab.tsx
src/components/common/controlTab/index.ts
src/components/features/vote/reply/Reply.stories.tsx
src/components/features/vote/reply/Reply.tsx
src/components/shared/endObserverList/EndObserverList.tsx
src/components/shared/index.ts
src/constants/options.ts
src/hooks/vote/index.ts
src/hooks/vote/useGetVoteReplies.ts
src/types/response.ts
src/types/vote/vote.ts
yarn.lock

- useInfiniteQuery를 활용한 댓글 무한 스크롤 조회
- 등록순/공감순 정렬 기능 (ControlTab 컴포넌트 작성)
- 스크롤 여부 확인을 위한 react-intersection-observer 라이브러리 설치
close #178 
- 라이브러리 설치로 yarn 실행 필요

[FEAT] 투표 댓글 infinite scroll 조회 및 정렬 기능

---

package.json
src/app/vote/[slug]/_component/Replies.tsx
src/components/shared/endObserverList/EndObserverList.tsx
src/components/shared/replyInput/ReplyInput.tsx
src/components/shared/replyInput/helper/replyReducer.ts
src/hooks/vote/index.ts
src/hooks/vote/useCreateVoteReplyMutation.ts
src/hooks/vote/useGetVotePaginatedReplies.ts
src/hooks/vote/useGetVoteReplies.ts
src/hooks/vote/useVoteReplyMutation.ts
yarn.lock

- immer 설치
- 댓글 조회 기능에서 페이지네이션 요청 제거 후 전체 댓글 api 요청으로 변경
- 댓글을 등록하면 마지막 페이지 데이터 다음에 새로운 댓글이 보여야 하는 상황
- 댓글 등록이 완료되기 위해선 모든 페이지가 순서대로 페칭되어야 하므로 오랜 시간이 소요되어 페이지네이션 제거
- 댓글 등록 기능 구현
- 댓글 등록 후 등록한 댓글 부분으로 스크롤 이동
- 댓글 등록은 optimistic update로 이루어짐
- 댓글 개수가 많아질 수록 api 응답이 오기까지 꽤 오랜 시간이 소요됨 (댓글 50개 정도로 테스트해봤을 때 약 7초 소요)
- 댓글이 실제로 등록되기까지 대기시키는 것보다 일단 UI를 업데이트하여 체감 속도를 줄이기 위해 optimistic update 적용
close #179

[FEAT] 댓글 등록 기능

---

src/app/vote/[slug]/_component/Replies.tsx
src/components/common/bottomSheet/style.css
src/components/features/vote/reply/Reply.stories.tsx
src/components/features/vote/reply/Reply.tsx
src/components/shared/confirmBottomSheet/ConfirmBottomSheet.tsx
src/components/shared/index.ts
src/components/shared/optionBottomSheet/OptionBottomSheet.tsx
src/components/shared/replyInput/ReplyInput.tsx
src/hooks/vote/index.ts
src/hooks/vote/useDeleteVoteReplyMutation.ts
src/hooks/vote/useUpdateVoteReplyMutation.ts

- 댓글 삭제 뮤테이션
- 옵션 선택 바텀시트, 확인용 바텀시트 컴포넌트 작성
close #184 
- 댓글 등록과 마찬가지로 .. 시간이 오래 걸리긴 합니다.

[FEAT] 댓글 삭제 기능

---

src/app/test/_components/TestForm.tsx
src/app/vote/[slug]/_component/Voting.tsx
src/components/common/toast/ToastContainer.tsx
src/contexts/toast/ToastProvider.tsx
src/hooks/useToast.tsx
src/hooks/vote/useCreateVoteReplyMutation.ts
src/hooks/vote/useDeleteVoteReplyMutation.ts
src/hooks/vote/useLikeVoteReplyMutation.ts
src/hooks/vote/useVotingMutation.ts

- 토스트가 인풋과 버튼을 가리지 않도록 위치 조정
close #192
- 토스트 컨테이너가 현재 화면에 인풋/버튼이 어디에 있고 그 높이는 어떠한지 알 수 없어서 props를 통해 얼만큼 마진을 둘지 받는 방법으로 대응했습니다.

[DESIGN] 토스트 노출 위치 수정

---

src/app/mypage/info/_components/NicknameForm.tsx
src/hooks/auth/index.ts
src/hooks/auth/types.ts
src/hooks/auth/useAuth.tsx
src/hooks/auth/useUpdateNicknameMutation.ts
src/schema/NicknameSchema.ts

- 닉네임 수정 뮤테이션
- 닉네임 수정 유효성 검사
close #28

[FEAT] 닉네임 수정 기능

---

src/constants/test/index.ts

- Vercel 에러 로그를 통해 알게 된 불필요한 변수를 삭제하였습니다.

[BUGFIX] 배포 환경에 불필요한 변수 삭제

---

src/app/test/_components/TestLoadingPage.tsx
src/app/test/_components/TestStep.tsx
src/app/test/result/[id]/page.tsx
src/utils/number.ts

1. 본질적인 해결책을 찾고 있습니다. 하지만 우선적으로 CSR에서 로딩시켜 3초후 바로 넘어가도록 구현하였습니다. 그럼에도 첫 방문시에는 1초의 지연이 발생합니다. 2번째부터는 의도한대로 작동
2. 시연 연상을 위해 임시로 정상 작동하도록 구현하였습니다. (애니메이션을 기존 프로그래스 바에서 제거 및 props 변경 예정입니다)

[REFACTOR] 시연 영상을 위한 테스트 결과 로딩 및 프로그래스바 임시 구현 

---

.github/ISSUE_TEMPLATE/-옹기종기--bug-report-template.md

[BUGFIX] 전역 yarn 1.22.19로 변경 

---

src/api/vote/types.ts
src/app/vote/[slug]/_component/Replies.tsx
src/components/shared/replyInput/ReplyInput.tsx
src/hooks/auth/useUpdateNicknameMutation.ts
src/hooks/vote/useCreateVoteReplyMutation.ts

댓글 등록 중에 노출되던 등록중... 문구를 현재 접속한 유저의 닉네임으로 변경

[FEAT] 댓글 등록 중 유저 닉네임 노출

---

.github/workflows/deployment.yml
package.json
src/app/test/_components/TestForm.tsx

발생 시점 : 맥북을 새롭게 구매한 후 (기존 M2 -> M1) 
해결 : 위의 에러를 해결하기 위해 여러 Package.json에서 packageManager을 삭제해서 해결 (https://stackoverflow.com/questions/78202142/vercel-this-projects-package-json-defines-packagemanager-yarn4-1-1-howe)
사이드 이펙트 에러가 있는지 확인해봐야할 것 같아요

[BUGFIX] vercel 배포 에러 해결 

---

src/app/vote/[slug]/_component/Replies.tsx

[BUGFIX] 댓글 등록 뮤테이트 후 스크롤
